# Authentication
LOGIN = "LOGIN"
PROFILE_LOGIN = "PROFILE_LOGIN"
LOGOUT = "LOGOUT"

# Subscription & billing
SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED"
FORCE_LOGOUT_SUB_EXPIRED = "FORCE_LOGOUT_SUB_EXPIRED"
PLAN_UPGRADE_PRIME_TO_VIP = "PLAN_UPGRADE_PRIME_TO_VIP"

# Session & security
DEVICE_BLOCKED = "DEVICE_BLOCKED"
SESSION_EXPIRED = "SESSION_EXPIRED"


PLAN_RENEWED = "PLAN_RENEWED"

